"""add password reset tokens

Revision ID: fce9a3e41eb2
Revises: 6babbea3e370
Create Date: 2026-09-17 12:13:16.335130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fce9a3e41eb2'
down_revision: Union[str, None] = '6babbea3e370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
